- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    vcenter_hostname: vc1-irv.techlab.com
    vcenter_user: Manikanta.Annam
    vcenter_pass: ChangeMeNow007!
    datacenter: IRV-LAB
    cluster: "fx2-vsan"
    vmtemplate: Server2016BaseGUI
    name: "Oiab_test2"
    notes: Ansible Test
    dumpfacts: False
  
  tasks:
   - name: Create VM from template
     vmware_guest:
       validate_certs: False
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_user }}"
       password: "{{ vcenter_pass }}"
       state: present
       cluster: "fx2-vsan"
       datacenter: "{{ datacenter }}"
       folder: "templates/Windows"
       name: "{{ name }}"
       template: "{{ vmtemplate }}"
       folder: "templates/Windows"
       networks:
         - name: vds-5k-core-servers-static
           ip: 10.10.68.237
           netmask: 255.255.254.0
           gateway: 10.10.68.1
           type: static
         - dns_servers: 10.10.98.198
       wait_for_ip_address: True
